# Generated by Django 5.0.6 on 2024-07-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table='myapp_photo',
        ),
    ]
